### ISSUE TITLE
Error en mailfy (linea 238)

### ISSUE THREAD

**Issue by Pepepy** [i3visio/osrframework#105]
En la linea 238 hay un error. creo que basta con quitar el 2015 para poder funcionar bien

File "mailfy.py", line 238, in main
    domains = args.domai2015ns

**Comment by i3visio** [comment]
Ooops... Huele a que sí. Lo miramos ahora mismo. ¡Gracias por el aviso!

**Comment by i3visio** [comment]
Efectivamente, ese era el error. Algún update en que se nos ha colado algo del portapapeles. Actualizado el repositorio de Github y liberada también la librería en pypi.python.org como versión 0.11.2. Puedes actualizar con:
```
sudo pip install osrframework --upgrade
```
Y probar mailfy.py con:
```
mailfy.py -m "i3visio@gmail.com"
```
O también:
```
mailfy.py -n "i3visio"
```
Cierro el _issue_ pero de todas formas si te surge alguna cosa nos comentas y lo reabrimos.
