### ISSUE TITLE
Consider adding beBee to supported platforms

### ISSUE THREAD

**Issue by nealrauhauser** [i3visio/osrframework#143]
http://bebee.com is growing rapidly, ten million users, some 35,000 new sign up daily. There is no API at this time but name to URL exploration is straightforward. I think this site is important enough to warrant attention.

**Comment by i3visio** [comment]
As a backlog, I'll add the URL structure and the error message and we will try to add the platform in the next update. URL structure: `https://es.bebee.com/perfil/<user>`. Error message: `<title>Abeja no encontrada (404) - beBee</title>`. 

Thanks for the notification.
