### ISSUE TITLE
Upgrading Issue while installation

### ISSUE THREAD

**Issue by FaizAlam** [i3visio/osrframework#221]
In README.md file for upgrading osrframwork, It is given that to upgrade use the following command-"pip install **osrframeworkr** --upgrade"  As we know this framework is _osrframework_ and not _osrframeworkr_. By running the given command it displays an error.
So I would request you to please correct it

**Comment by i3visio** [comment]
:man_facepalming: You're right! It was an important typo and it's fixed now. Thanks for the report!

**Comment by FaizAlam** [comment]
Thank a lot for the change.
