### ISSUE TITLE
Problem with searchfy on facebook

### ISSUE THREAD

**Issue by Tudorvr** [i3visio/osrframework#263]
Is there any problem using searchfy module on facebook? Anything I now search.. I don`t get any results... And it worked so nice before( last weeek for e.g.)

**Comment by i3visio** [comment]
You're right. Something might have changed on Facebook. We will go through it during the weekend to try to fix it up as soon as possible. Thanks for the feedback!

**Comment by Tudorvr** [comment]
You`re very welcome. Isee that Entify also doesn`t return results anymore from Facebook.

**Comment by Tudorvr** [comment]
searchfy is working now. Thank you!
