### ISSUE TITLE
Copying relevant files error on Mac OS X

### ISSUE THREAD

**Issue by aabilio** [i3visio/osrframework#271]
It seems that in Mac OS X (tested on 10.11.4) the flags of "cp" needs to be at the beginning of the command before the _from_/_to_ parameters.
So the relevant files are not copying well at installation process..

**Comment by i3visio** [comment]
Merged in master as https://github.com/i3visio/osrframework/commit/31f7813b89a3a38d503e376ce9fa1e2abce0ed68 (soon it will be released as alpha/beta version). Thanks for the effort!

**Comment by aabilio** [comment]
Thanks to you @i3visio, it is a very useful a framework ;) a framework ;)
