### ISSUE TITLE
searchfy.py: Segmentation fault on MacOS X (10.11.4)

### ISSUE THREAD

**Issue by aabilio** [i3visio/osrframework#273]
<img width="1115" alt="captura de pantalla 2017-07-03 a las 21 09 18" src="https://user-images.githubusercontent.com/664712/27805293-2b339c3c-6034-11e7-95da-73c3349e70e4.png">

Debugging a little I could verify that the error **occurs at Skype4Py external lib** when the Skype app is not running

**Comment by i3visio** [comment]
Merged in master too as in https://github.com/i3visio/osrframework/commit/31f7813b89a3a38d503e376ce9fa1e2abce0ed68 (soon it will be released as alpha/beta version). Thanks for the effort again!
