### ISSUE TITLE
add email domains

### ISSUE THREAD

**Issue by andrewfnam** [i3visio/osrframework#292]
can you add email domains of yahoo.com and hotmail.com
Thanks

**Comment by i3visio** [comment]
Unfortunately, we cannot add this using the current approach. Both Yahoo and Hotmail are not working with the Python libraries that we are currently using (for Python2, `emailahoy` and `validate_email` libraries). 

Currently, we now that this can be done manually by trying to start up a sign in process in the login websites of the platforms. Though, we have not been able to automate this process till now. Anyway, if there is another approach that we can consider, we will try to have a look at it.
