### ISSUE TITLE
something it's interesting...

### ISSUE THREAD

**Issue by tahwgithub** [i3visio/osrframework#295]
# ./osrfconsole.py 

=============================

osrf > exit
Traceback (most recent call last):
  File "./osrfconsole.py", line 1003, in <module>
    OSRFConsoleMain().cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./osrfconsole.py", line 998, in do_exit
    print(info("Exiting..."))
NameError: global name 'info' is not defined

=========================================== then after i  have deleting the ""info"" and ""()""

so  is that print("Exiting..")
==================================
osrf > exit
Exiting...
==============
lol~~~~

**Comment by i3visio** [comment]
Confirmed and triaged. Thanks for the report!

**Comment by febrezo** [comment]
In the end, we have fixed this in 0.17.4. Available now ;)
