### ISSUE TITLE
Agregar dependencia en la documentación. (Si es que lo consideran apropiado)

### ISSUE THREAD

**Issue by pablovidelayanez** [i3visio/osrframework#30]
Hola chicos, los conoci a través de la charla de la 8.8 en Santiago, Chile.
Estaba instalando todo lo necesario para probar su sistema y al instalar las dependencias o modulos de python me salio esto.
 

============================================================================

                        * The following required packages can not be built:

                        * freetype, png

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/matplotlib
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/matplotlib
--------------------

Pero lo corregi con esto: *apt-get install libfreetype6-dev* , seguramente muchos de los que prueban o probaran su sistema no tienen esa dependencia por defecto y les saltará este problema.

Saludos!.

**Comment by i3visio** [comment]
Tomamos nota. Por curiosidad, ¿lo estás lanzando en Debian/Ubuntu? ¿Qué versión? Por aquello de tenerlo identificado, si lo confirmamos le pasamos la dependencia al instalador del paquete y resuelto.

**Comment by pablovidelayanez** [comment]
Uso esta versión Ubuntu 14.04.3 LTS (GNU/Linux 3.16.0-30-generic x86_64).

Recuerden que instale con apt el osrframework y despues hice todo el llamado a la instalación con pip, tal como sale en la documentación, saludos y felicitaciones nuevamente.

**Comment by i3visio** [comment]
Puedes probar a instalar con pip. Debería resolver las dependencias directamente con:
```
sudo pip install osrframework
```
Si ya lo tenías instalado, puede ser que necesites ejecutarlo con la opción --upgrade:
```
sudo pip install osrframework --upgrade
```
