### ISSUE TITLE
Skype4Py does not work with current Skype API, please disable skype features

### ISSUE THREAD

**Issue by rhertzog** [i3visio/osrframework#300]
Hello,

it looks like that Skype4Py does not work with current Skype API so you should probably remove (or at least disable) all the features that rely on this module (until it's fixed, if it ever gets fixed). Looking at the github ticket https://github.com/Skype4Py/Skype4Py/issues/81 it looks like there's no sign of any activity there.

Thank you.

BTW it would be nice if you could create git tags when you make releases to pypi.

**Comment by i3visio** [comment]
Thanks @rhertzog. We are preparing a release for 0.18.0 and we will fix this until we can find an alternative way of doing this again.
