### ISSUE TITLE
alias_generator fails with "main() got unexpected keyword argument 'name' "

### ISSUE THREAD

**Issue by sbrun** [i3visio/osrframework#302]
Hello,

In new version 0.18.0, run alias_generator, provide requested informations, then it fails with the message:
```
Traceback (most recent call last):
  File "/usr/local/bin/alias_generator", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/osrframework/alias_generator.py", line 2915, in main
    extraWords=extraWords
TypeError: main() got an unexpected keyword argument 'name'
```
The problem is there are 2 functions named "main" in alias_generator.py. I think the first function main should be renamed. 
But it's not enough to fix the issue: "args" is not defined in the first function main but it's used line 2811 and 2813.

**Comment by i3visio** [comment]
Wow. You're right. Thanks for the report. Labelling it to be fixed soon.
