### ISSUE TITLE
Searchfy problemas con skype

### ISSUE THREAD

**Issue by pablovidelayanez** [i3visio/osrframework#31]
X11 connection rejected because of wrong authentication.
ERROR: something happened when trying to link to Skype.

Me sale eso al momento de usar searchfy. 

En todo caso los resultados me salen igual, felicidades por la herramienta, muy util.

**Comment by i3visio** [comment]
Buenas Pablo,

¿Tienes instalado Skype y estás logueado con alguna cuenta? No lo decíamos, pero para que searchfy (y usufy también) pueda enlazar con Skype tienes que estar logueado con el cliente corriendo. La primera vez que lo ejecutas tienes que estar pendiente porque Skype te lanza en su interfaz un aviso de que una aplicación de un tercero está intentando acceder a la aplicación. Le tienes que dar a aceptar y puedes marcar también la opción de recordar para que no te solicite los permisos cada vez que la lanzas. 

Compruébalo y nos dices.

**Comment by pablovidelayanez** [comment]
Hola, donde lo probe no tenía instalado skype y no puedo instalarlo porque estoy desde ssh y no tengo acceso con interfaz gráfica por el momento, esto se podría probar en windows?

**Comment by i3visio** [comment]
Sí, debería funcionar y de hecho lo hemos tenido funcionando asi bastante tiempo. La instalación la deberías hacer clonando desde Git. El problema es que con estas versiones en prueba hasta que no saquemos una release verdaderamente estable no podemos garantizarte la compatibilidad en todos los SO al 100%. :(

**Comment by pablovidelayanez** [comment]
En windows lo tengo clonado, lo instalaré apenas pueda en mi tiempo libre, les cuento cualquier cosa durante la semana, saludos.

**Comment by telebuss** [comment]
A mí me sale el mismo problema, me dice que no se puede conectar a Skype. 
Abrí Skype, me conecté con mi cuenta de usuario, e hice una búsqueda. Se abre una página de Skype, pero está en blanco. En el terminal me avisa de que hay errores para conectar a Skype, pero no puedo darle a ningun botón en la que supongo que es la página de me permita permitir a usufy acceder.
Estoy usando una distro de Ubuntu 14.04 LTS con Unity

**Comment by telebuss** [comment]
Yo tengo un problema parecido. Hace unos segundos posteé que cuando ejecutaba una búsqueda, me indicaba también que hay un error al conectar a _Skype_. Me di cuenta de que estaba ejecutando siempre la aplicación con __sudo__, y al ejecutar solo __usufy.py__ y luego la búsqueda, me sale la página de acceso a Skype, pero luego me dice que 
> IOError: [Errno 13] Permission denied: './results/profiles.csv'

Por tanto, vuelvo a intentar ejecutar con __sudo__, pero me sale de nuevo el error de acceso a Skype, aunque he marcado que lo recuerde.
¿Alguna idea?

PD: El programa es increíble. :smile:

**Comment by i3visio** [comment]
Buenas telebuss, estábamos buscando tu post anterior y ya lo habías borrado. Aunque también puede ser que antes se creara el archivo como root y ahora los estés ejecutando con tu usuario normal, el error de permission denied es típico también de cuando aún tienes abierto el archivo .csv o .xls después de haber mirado los resultados de una investigación anterior.

El programa ahora mismo no verifica si el archivo está abierto y directamente si no puede tira la excepción. Inténtalo de nuevo y nos dices.

PD: de todas formas creamos una issue nueva para que si no puede escribirlo en el fichero lo intente creando otro fichero y, al menos, no perder las búsquedas realizadas

**Comment by telebuss** [comment]
Encontré el error. Menuda torpeza la mía, estaba intentando ejecutar el programa en /home, y para poder escribir ahí me pide permisos root. En cuanto lo he ejecutado en una carpeta con permisos para escribir, y se ha ejecutado perfectamente.
Gracias por la rápida respuesta.
