### ISSUE TITLE
Algunos errores en la busqueda con usufy

### ISSUE THREAD

**Issue by pablovidelayanez** [i3visio/osrframework#32]
Salen falsos positivos, creo que cambiaron los mensajes de error de las siguientes plataformas o bien puede ser el lenguaje de cada mensaje de error, en ebay esta en ingles pero si entro personalmente me sale el mensaje de error en español, puede ser eso?
Ebay
Burbuja.info
arto.com
jamiiforums.com

Saludos.

**Comment by i3visio** [comment]
Puede ser. En la máquina en la que lo estamos lanzando nosotros el error no aparece. Intentaremos

La de Burbuja.info está arreglada y actualizada en la nueva versión. En Jamiiforums parece que han introducido mecanismos adicionales de verificación, por lo que llevará un poco más de tiempo parece. En cualquier caso, cerramos este issue y creamos issues paralelos en #33, #34 y #35 para hacer seguimiento individual e intentar atajarlos cuando saquemos algo de tiempo, aunque esta semana es algo complicado.

**Comment by i3visio** [comment]
Por cierto, debería estar actualizado en la versión 0.9.10. Si ya añadiste el repositorio:
```
sudo apt-get update
sudo apt-get upgrade
```

**Comment by pablovidelayanez** [comment]
Perfecto, también podría aportar con codigo , agregar mas plataformas, debo hacer un nuevo branch para eso o como podría aportar sin interferir con su repositorio?

**Comment by i3visio** [comment]
No sabemos si está familiarizado con Git, pero lo que tendrías que hacer sería un Fork del proyecto original. Después, en local, crearías una rama nueva en la que podrías incluir los cambios en cuestión. 
Una vez hecho, tendrías que subir tu repositorio y enviarnos un pull request para que incorporemos los cambios en la versión «oficial» del proyecto y todos los usuarios que lo utilicen lo puedan usar. No es sencillo si no lo has hecho nunca, pero puedes encontrar más detalles en este link <http://aprendegit.com/que-es-un-pull-request/> o en este otro <http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request>.

De todas formas, si tienes alguna duda a este respecto, coméntanos y te vamos ayudando. ;)

**Comment by pablovidelayanez** [comment]
Trabajo con git, solo que jamás con proyectos open source, sólo repositorios privados, pero ya me has sacado la duda, gracias. Voy a hacer el fork. Cualquier cosa me comunico con ustedes.

Saludos y gracias!.
