### ISSUE TITLE
Cannot install OSRFramework on Kali Linux

### ISSUE THREAD

**Issue by PingRequest** [i3visio/osrframework#329]
python --version gives me 2.7.14+
pip --version gives me 
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

I have tried:
pip uninstall osrframework

which reveals 
Cannot uninstall requirement osrframework, not installed

So, I try 
pip install osrframework --user

and I get

  Using cached https://files.pythonhosted.org/packages/e3/57/bb270f90c7912f000cf80cfa633cf1eb2848295aebd349282df51af4f0de/osrframework-0.20.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NuScGW/osrframework/setup.py", line 161
        print(f"\t> {cmd}")
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NuScGW/osrframework/

-----

I've also tried 
pip2 install osrframework 
(with and without the --user option) and get the same result.

What am I doing wrong, and how can I fix this?

Thank you.

**Comment by febrezo** [comment]
Yep! OSRFramework > 0.20 uses Python3. The syntax highlighted is a f-string which only appears in Python 3.6+:
```
 print(f"\t> {cmd}")
```

To install it, you need to install:
```
pip3 install osrframework --upgrade
```

If you are not root use:

```
pip3 install osrframework --upgrade --user
```
