### ISSUE TITLE
Error starting up

### ISSUE THREAD

**Issue by Samuel20354** [i3visio/osrframework#371]
So i installed the framework but when i run `sudo osrf --help` i get:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/osrframework/utils/configuration.py", line 119, in get_configuration_values_for
    with open(defaultConfigPath) as iF:
FileNotFoundError: [Errno 2] No such file or directory: '/home/samuel20354/.config/OSRFramework/default/general.cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/osrf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/osrframework/launcher.py", line 136, in main
    parser = get_parser()
  File "/usr/local/lib/python3.9/dist-packages/osrframework/launcher.py", line 80, in get_parser
    parents=[checkfy.get_parser()]
  File "/usr/local/lib/python3.9/dist-packages/osrframework/checkfy.py", line 84, in get_parser
    DEFAULT_VALUES = configuration.get_configuration_values_for("checkfy")
  File "/usr/local/lib/python3.9/dist-packages/osrframework/utils/configuration.py", line 125, in get_configuration_values_for
    raise errors.DefaultConfigurationFileNotFoundError(configPath, defaultConfigPath);
osrframework.utils.errors.DefaultConfigurationFileNotFoundError: 
	- Oh! What's happening? > The configuration file /home/samuel20354/.config/OSRFramework/general.cfg could not be found. The system tried to get the files provided by default with OSRFramework but they were not found either.
	- How can I solve this? > Check if the configuration path exists or if it is accesible by the current user. You should be able to find the default configuration files at '/home/samuel20354/.config/OSRFramework/default/general.cfg'. If they are not there, try to solve this by reinstalling OSRFramework again for this user.
	- This is not enough... > If you need more information on how to solve this, copy this information and ask us by placing an issue at <https://github.com/i3visio/osrframework/issues>.

I have tried reinstalling it and upgrading it but it hasn't worked

**Comment by elshobokshy** [comment]
I've got the same error for the record

**Comment by Samuel20354** [comment]
Thanks it worked

**Comment by elshobokshy** [comment]
@Samuel20354 for future reference on Google kindly change the title of the issue to "FileNotFoundError: No such file or directory general.cfg"

**Comment by Samuel20354** [comment]
Thanks it works now

**Comment by Darkstar-93** [comment]
thanks @elshobokshy it worked! But why does manually creating the file do anything? any feedback appreciated!
